;------------------------
; example kinematics file for "from_file", using Fourier descriptors for the wingbeat
; NOTE: this file describes one wingbeat that repeats periodically after time=1
;------------------------
[kinematics]
; if the format changes in the future
format=2015-10-09; currently unused
convention=flusi;
; what units, radiant or degree?
units=degree;
; is this hermite or Fourier coefficients?
type=fourier;


; nfft=1 means we expect one value for each of ai,bi (and the constant a0)
; The Fourier series evaluation in WABBIT/FLUSI is :
; Q = a0_Q / 2 + ( a1_Q*sin(1*2*pi*t) + b1_Q*sin(1*2*pi*t) )
;              + ( a2_Q*sin(2*2*pi*t) + b2_Q*sin(2*2*pi*t) )
;              + ....
; Note the unfortunate division of a0 by 2, which is an historic artifact.

;------------------------
; phi (positional angle)
nfft_phi=5;
a0_phi=15.66300920;
ai_phi=20.11636045	  2.49360176	  1.66573313	  0.02585923	  0.07589448;
bi_phi=-2.93130024	  0.01488171	  0.31698294	 -0.01703334	  0.06056280;
;------------------------
; alpha (feathering angle)
nfft_alpha=5;
a0_alpha=-12.78941423;
ai_alpha=6.75313440	  2.27642124	  2.14089605	  0.14161375	  0.15168858;
bi_alpha=37.99026820	  2.50003175	  2.59125561	 -0.14515907	 -0.10412793;
;------------------------
; theta (deviation angle)
nfft_theta=1;
a0_theta=-32;
ai_theta=0;
bi_theta=0;
