;------------------------
; example kinematics file for "from_file", using Fourier descriptors for the wingbeat
; NOTE: this file describes one wingbeat that repeats periodically after time=1
;------------------------
[kinematics]
; if the format changes in the future
format=2015-10-09; currently unused
convention=flusi;
; what units, radiant or degree?
units=degree;
; is this hermite or Fourier coefficients?
type=fourier;


; nfft=1 means we expect one value for each of ai,bi (and the constant a0)
; The Fourier series evaluation in WABBIT/FLUSI is :
; Q = a0_Q / 2 + ( a1_Q*sin(1*2*pi*t) + b1_Q*sin(1*2*pi*t) )
;              + ( a2_Q*sin(2*2*pi*t) + b2_Q*sin(2*2*pi*t) )
;              + ....
; Note the unfortunate division of a0 by 2, which is an historic artifact.

;------------------------
; phi (positional angle)
nfft_phi=5;
a0_phi=15.47820292;
ai_phi=-4.94161425	  0.00381988	 -0.12692235	 -0.07973036	 -0.12368882;
bi_phi=-16.64452714	 -0.74204852	 -0.74125446	  0.01435034	  0.04656294;
;------------------------
; alpha (feathering angle)
nfft_alpha=5;
a0_alpha=-7.79900118;
ai_alpha=30.18492744	  0.20662278	  1.71316462	 -0.11792991	 -0.12734700;
bi_alpha=-15.46637437	  1.36502871	  0.20203048	 -0.01797993	 -0.05040715;
;------------------------
; theta (deviation angle)
nfft_theta=0;
a0_theta=0;
ai_theta=0;
bi_theta=0;
